workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "reunification"'
      when: always
    - when: never

stages:
  - deploy

variables:
  SOURCE_PROJET: "/mnt/data/vicitelecom/Ari_IA_AgentFrontend"

deploy_projet:
  stage: deploy
  tags:
    - linux
    - production
    - serveur

  script:
    - echo "Lancement CI-CD Front"
    - cd "$SOURCE_PROJET"
    - cp -f ProcessLog.tsx /mnt/data/pm2_web/pm2.web/apps/dashboard/components/process/
    - pm2 restart 25
    - sleep 15
    - pm2 logs pm2.web-dashboard --lines 15 --nostream

  after_script:
    - echo "✅ Déploiement terminé"