workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "reunification"'
      when: always
    - when: never

stages:
  - deploy

variables:
  SOURCE_PROJET: "/mnt/data/vicitelecom/Ari_IA_AgentFrontend"

deploy_projet:
  stage: deploy
  tags:
    - linux
    - production
    - serveur

  script:
    - echo "Lancement CI-CD Front"
    - cd "$SOURCE_PROJET"
    - git remote -v
    - git pull origin reunification
    - pm2 restart 18

  after_script:
    - echo "✅ Déploiement terminé"