workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "reunification"'
      when: always
    - when: never

stages:
  - deploy

variables:
  SOURCE_PROJET: "/mnt/data/vicitelecom"

deploy_projet:
  stage: deploy
  tags:
    - linux
    - production
    - serveur

  script:
    - echo "Lancement CI-CD Front"
    - ls

  after_script:
    - echo "✅ Déploiement terminé"