workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "reunification"'
      when: always
    - when: never

stages:
  - deploy

variables:
  SOURCE_PROJET: "/mnt/data/vicitelecom/Ari_IA_AgentFrontend"

deploy_projet:
  stage: deploy
  tags:
    - linux
    - branche
    - ubuntu

  script:
    - echo "🚀 Encore un test..."
    - cd "$SOURCE_PROJET"
    - git remote -v
    - ls

  after_script:
    - echo "✅ Déploiement terminé"